=== icecello/devgui2-calendar/src/XML/calendar.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT calendar (dayEvent)*>
<!ELEMENT dayEvent (name, startDate, endDate, category, priority)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT startDate (#PCDATA)>
<!ELEMENT endDate (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT priority (#PCDATA)>

=== icecello/devgui2-calendar/trunk/src/XML/calendar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE calendar SYSTEM "calendar.dtd">

<calendar>
  <dayEvent>
    <name>First event</name>
    <startDate>2010-mar-26 10:27:20</startDate>
    <endDate>2010-mar-26 11:27:20</endDate>
    <category>Home</category>
    <priority>LOW</priority>
  </dayEvent>
  <dayEvent>
    <name>Second Event</name>
    <startDate>2010-mar-27 10:27:20</startDate>
    <endDate>2010-mar-27 11:27:20</endDate>
    <category>Home</category>
    <priority>LOW</priority>
  </dayEvent>
</calendar>

=== icecello/devgui2-calendar/src/XML/calendar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE calendar SYSTEM "calendar.dtd">

<calendar>
  <dayEvent>
    <name>test2</name>
    <startDate>2010-05-13 20:29</startDate>
    <endDate>2010-05-13 21:29</endDate>
    <category>catEdit</category>
    <priority>MEDIUM</priority>
  </dayEvent>
  <dayEvent>
    <name>test</name>
    <startDate>2010-05-12 20:29</startDate>
    <endDate>2010-05-12 21:29</endDate>
    <category>cat</category>
    <priority>MEDIUM</priority>
  </dayEvent>
</calendar>
