=== icecello/devgui2-calendar/src/XML/categories.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT categories (category)*>
<!ELEMENT category (name, description?, color?, icon?)>
<!ELEMENT name (#PCDATA) >
<!ELEMENT description (#PCDATA)>



<!--
All of red, green, and blue should contain a integer value between 0 - 255
that describes the amount of red, green, and blue, respectively.
-->
<!ELEMENT color EMPTY>
<!ATTLIST color
    red CDATA #REQUIRED
    green CDATA #REQUIRED
    blue CDATA #REQUIRED>
    
<!--
icon should contain the qualified filename of the image.
Eg. /src/image/icons/default_icon.ppm
-->
<!ELEMENT icon EMPTY>
<!ATTLIST icon src CDATA #REQUIRED>

=== icecello/devgui2-calendar/trunk/src/XML/categories.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE categories SYSTEM "categories.dtd">

<categories>
  <category>
    <name>new Cat</name>
    <description />
    <color red="75" green="255" blue="75" />
  </category>
  <category>
    <name>sommarlov</name>
    <description>Ledig tid tills jobbet b√∂rjar!!!</description>
    <color red="75" green="195" blue="135" />
  </category>
</categories>

=== icecello/devgui2-calendar/src/XML/categories.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE categories SYSTEM "categories.dtd">

<categories>
  <category>
    <name>category1</name>
    <description>
        Short description
    </description>
    <color red="100" green="200" blue="200"/>
  </category>
  <category>
    <name>category2</name>
    <description>This is the second event</description>
    <color red="200" green="100" blue="100"/>
    <icon src=""/>
  </category>
</categories>
